<?php
/**
 * @var $block
 */
?>
<div class="landingPage">
    <div class="top">
        <div class="cleverreachLogo">
            <img src="<?= $this->getViewFileUrl('CleverReach_Plugin::images/cleverreach.png'); ?>"/>
        </div>
        <div class="clientId">
            Client ID: <?= $block->getClientId() ?>
        </div>
    </div>
    <div class="status">
        <div>Sync Status:</div>
        <div class="statusProgress" id="statusValue">In progress</div>
    </div>
    <div class="buttonDiv">
        <button class="connectButton" onclick="Demomagento.syncService.manualSync()"> Synchronize</button>
    </div>
</div>
<input type="hidden" value="<?= $block->getSynchronizationUrl(); ?>" id="syncUrl">
<input type="hidden" value="<?= $block->getSyncStatusUrl(); ?>" id="checkSyncUrl">
<input type="hidden" value="<?= $block->getManualSynchronizationUrl(); ?>" id="manualSyncUrl">

