name: Deploy to Stage

on:
  pull_request:
    types: [closed]
    branches: [staging]

jobs:
  deploy:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.body, '- [x] Deploy to stage environment')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Stage Shop
        run: |
          echo "Deploying to staging shop..."